# File: .github/workflows/release.yml
name: Release Production Build

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      new_pubspec_version: ${{ steps.get_new_pubspec_version.outputs.next_pubspec_version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare .releaserc
        run: mv .releaserc.prod.json .releaserc.json

      - name: Get latest prod tag
        id: get_latest_prod_release
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          prefix: "release/prod/"
          fallback: 0.0.1+0

      - name: Calculate semver
        id: semantic_release_info
        uses: cycjimmy/semantic-release-action@v3.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_AUTOMATOR_PAT }}
        with:
          semantic_version: 19

      - name: Update pubspec.yaml
        id: get_new_pubspec_version
        run: |
          prev="${{ steps.get_latest_prod_release.outputs.tag }}"
          prev_clean=$(echo "$prev" | sed -E "s/release\/prod\/(.*)/\1/")
          semver="${{ steps.semantic_release_info.outputs.new_release_version }}"
          next_version=$(./scripts/semver.sh "$prev_clean" "$semver")
          sed -Ei "s/^version: .*/version: $next_version/" pubspec.yaml
          echo "next_pubspec_version=$next_version" >> $GITHUB_OUTPUT

      - name: Commit version bump
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(release): bump to version ${{ steps.get_new_pubspec_version.outputs.next_pubspec_version }} [skip ci]"

      - name: Tag release
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "release/prod/${{ steps.get_new_pubspec_version.outputs.next_pubspec_version }}"
          message: "Production release ${{ steps.get_new_pubspec_version.outputs.next_pubspec_version }}"
          github_token: ${{ secrets.RELEASE_AUTOMATOR_PAT }}

  build-web:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.6
      - run: flutter pub get
      - run: flutter build web --release
      - run: zip -r web.zip build/web
      - uses: actions/upload-artifact@v3
        with:
          name: web-release
          path: web.zip

  build-android:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.6
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v3
        with:
          name: android-release
          path: build/app/outputs/flutter-apk/app-release.apk

  build-linux:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.6
      - run: flutter pub get
      - run: flutter build linux
      - run: zip -r linux.zip build/linux
      - uses: actions/upload-artifact@v3
        with:
          name: linux-release
          path: linux.zip

  build-windows:
    needs: release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.6
      - run: flutter pub get
      - run: flutter build windows
      - run: Compress-Archive -Path build/windows -DestinationPath windows.zip
      - uses: actions/upload-artifact@v3
        with:
          name: windows-release
          path: windows.zip

  build-macos:
    needs: release
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.6
      - run: flutter pub get
      - run: flutter build macos --release
      - run: zip -r macos.zip build/macos/Build/Products/Release/Runner.app
      - uses: actions/upload-artifact@v4
        with:
          name: macos-release
          path: macos.zip

  publish-release:
    needs:
      - build-web
      - build-android
      - build-linux
      - build-windows
      - build-macos
      - release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release/prod/${{ needs.release.outputs.new_pubspec_version }}
          name: Release ${{ needs.release.outputs.new_pubspec_version }}
          prerelease: false
          draft: false
          body: ${{ needs.release.outputs.release_notes }}
          files: |
            dist/web-release/web.zip
            dist/android-release/app-release.apk
            dist/linux-release/linux.zip
            dist/windows-release/windows.zip
            dist/macos-release/macos.zip