---
# .github/workflows/flutter-release.yml
# Triggered on tag push to main (e.g., v1.2.3)

name: Flutter Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.5
      - run: flutter pub get
      - run: flutter analyze --no-fatal-infos --no-fatal-warnings
      - run: flutter test

  build-linux:
    runs-on: ubuntu-latest
    needs: analyze-and-test
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.5
      - run: sudo apt-get update && sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: flutter build linux
      - run: zip -r linux-release.zip build/linux/x64/release/bundle/
      - uses: softprops/action-gh-release@v1
        with:
          files: linux-release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest
    needs: analyze-and-test
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.5
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter build windows
      - run: Compress-Archive -Path build\windows\runner\Release\* -DestinationPath windows-release.zip
      - uses: softprops/action-gh-release@v1
        with:
          files: windows-release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-android:
    runs-on: ubuntu-latest
    needs: analyze-and-test
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.5
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-web:
    runs-on: ubuntu-latest
    needs: analyze-and-test
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.5
      - run: flutter pub get
      - run: flutter build web --release
      - run: zip -r web-release.zip build/web/
      - uses: softprops/action-gh-release@v1
        with:
          files: web-release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
