---
# File: .github/workflows/flutter-snapshot-ci.yml
name: Snapshot CI

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  schedule:
    # Runs daily at 00:00 UTC (adjust as needed)
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering of snapshot builds

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.6
      - name: Get Flutter Dependencies
        run: flutter pub get
      - name: Build Web Release
        run: flutter build web
      - name: Zip Web Artifact
        run: zip -r web.zip build/web/
      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-snapshot
          path: web.zip
          retention-days: 1 # Keep artifacts for a short period

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.6
      - name: Get Flutter Dependencies
        run: flutter pub get
      - name: Build Android APK Release
        run: flutter build apk
      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-snapshot
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 1

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.6
      - name: Install Linux Dependencies
        run: sudo apt-get update && sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev
      - name: Enable Linux Desktop
        run: flutter config --enable-linux-desktop
      - name: Get Flutter Dependencies
        run: flutter pub get
      - name: Build Linux Release
        run: flutter build linux
      - name: Zip Linux Artifact
        run: zip -r linux.zip build/linux/x64/release/bundle
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-snapshot
          path: linux.zip
          retention-days: 1

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.6
      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop
      - name: Get Flutter Dependencies
        run: flutter pub get
      - name: Build Windows Release
        run: flutter build windows
      - name: Zip Windows Artifact
        run: powershell Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath windows.zip
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-snapshot
          path: build/windows/x64/runner/Release/
          retention-days: 1

  build-macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
         flutter-version: 3.32.6
      - run: flutter pub get
      - run: flutter build macos
      - run: zip -r macos.zip build/macos/Build/Products/Release/chummer5x.app
      - uses: actions/upload-artifact@v4
        with:
          name: macos-snapshot
          path: macos.zip
  
  upload-artifacts:
    if: github.event_name == 'push'
    needs: [build-web, build-android, build-linux, build-windows, build-macos]
    name: Upload Snapshot Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Delete existing snapshot tag and release (if any)
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          tag_name: snapshot-latest
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_FOR_WORKFLOW_TRIGGER }}
      - name: Download Snapshot Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Upload to GitHub Snapshot Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_FOR_WORKFLOW_TRIGGER }}
        with:
          tag_name: snapshot-latest
          name: "Daily Snapshot Build (${{ github.sha }})"
          body: |
            Latest Snapshot Build

            This is an automated daily snapshot build from the `development` branch.

            Commit SHA: `${{ github.sha }}`
            Triggered by: `${{ github.event_name }}`

            Artifacts:
            - Web: web-snapshot.zip
            - Linux: linux-snapshot.zip
            - Windows: windows-snapshot.zip
            - Android: android-snapshot.apk
            - macOS: macos-snapshot.zip

            Please test thoroughly and report any issues.
          prerelease: true
          files: |
            dist/web-snapshot/web.zip
            dist/linux-snapshot/linux.zip
            dist/windows-snapshot/windows.zip
            dist/android-snapshot/app-release.apk
            dist/macos-snapshot/macos.zip

