---
# .github/workflows/flutter-release.yml
# Triggered on tag push (e.g., v1.2.3) to main

name: Flutter Release

on:
  push:
    tags:
      - 'v*.*.*' # This pattern matches tags like v1.0.0, v1.2.3, etc.

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.6
      - name: Get Flutter Dependencies
        run: flutter pub get
      - name: Analyze Code
        run: flutter analyze --no-fatal-infos --no-fatal-warnings
      - name: Run Tests
        run: flutter test

  build-linux:
    runs-on: ubuntu-latest
    needs: analyze-and-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.6
      - name: Install Linux Dependencies
        run: sudo apt-get update && sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev
      - name: Enable Linux Desktop
        run: flutter config --enable-linux-desktop
      - name: Get Flutter Dependencies
        run: flutter pub get
      - name: Build Linux Release
        run: flutter build linux
      - name: Zip Linux Release
        run: zip -r linux-release.zip build/linux/x64/release/bundle/
      - name: Create GitHub Release (Linux)
        uses: softprops/action-gh-release@v1
        with:
          files: linux-release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest
    needs: analyze-and-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.6
      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop
      - name: Get Flutter Dependencies
        run: flutter pub get
      - name: Build Windows Release
        run: flutter build windows
      - name: Compress Windows Release
        run: Compress-Archive -Path build\windows\runner\Release\* -DestinationPath windows-release.zip
      - name: Create GitHub Release (Windows)
        uses: softprops/action-gh-release@v1
        with:
          files: windows-release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-android:
    runs-on: ubuntu-latest
    needs: analyze-and-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.6
      - name: Get Flutter Dependencies
        run: flutter pub get
      - name: Build Android APK Release
        run: flutter build apk --release
      - name: Create GitHub Release (Android)
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-web:
    runs-on: ubuntu-latest
    needs: analyze-and-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.6
      - name: Get Flutter Dependencies
        run: flutter pub get
      - name: Build Web Release
        run: flutter build web --release
      - name: Zip Web Release
        run: zip -r web-release.zip build/web/
      - name: Create GitHub Release (Web)
        uses: softprops/action-gh-release@v1
        with:
          files: web-release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
