---
# .github/workflows/flutter-snapshot.yml
# CI build for feature and development branches, plus PRs

name: Flutter Snapshot CI

on:
  push:
    branches:
      - development # Trigger on pushes to the development branch
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
  
jobs:
  analyze-and-test:
    # Only run for non-draft pull requests or pushes to development
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.6

      - name: Get Flutter Dependencies
        run: flutter pub get
      
      - name: Analyze Code
        run: flutter analyze --no-fatal-infos --no-fatal-warnings
      
      - name: Run Tests
        run: flutter test

  build-web:
    # Only run for non-draft pull requests or pushes to development
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    needs: analyze-and-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.6
      - name: Get Flutter Dependencies
        run: flutter pub get
      - name: Build Web Release
        run: flutter build web --release
      - name: Upload Web Snapshot Artifact
        uses: actions/upload-artifact@v4
        with:
          name: snapshot-web
          path: build/web/
          retention-days: 60

  build-linux:
    # Only run for non-draft pull requests or pushes to development
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    needs: analyze-and-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.6
      - name: Install Linux Dependencies
        run: sudo apt-get update && sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev
      - name: Enable Linux Desktop
        run: flutter config --enable-linux-desktop
      - name: Get Flutter Dependencies
        run: flutter pub get
      - name: Build Linux Release
        run: flutter build linux
      - name: Upload Linux Snapshot Artifact
        uses: actions/upload-artifact@v4
        with:
          name: snapshot-linux
          path: build/linux/x64/release/bundle/
          retention-days: 60

  build-windows:
    # Only run for non-draft pull requests or pushes to development
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    runs-on: windows-latest
    needs: analyze-and-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.6
      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop
      - name: Get Flutter Dependencies
        run: flutter pub get
      - name: Build Windows Release
        run: flutter build windows
      - name: Upload Windows Snapshot Artifact
        uses: actions/upload-artifact@v4
        with:
          name: snapshot-windows
          path: build/windows/x64/runner/Release/
          retention-days: 60

  build-android:
    # Only run for non-draft pull requests or pushes to development
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    needs: analyze-and-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.6
      - name: Get Flutter Dependencies
        run: flutter pub get
      - name: Build Android APK Release
        run: flutter build apk --release
      - name: Upload Android Snapshot Artifact
        uses: actions/upload-artifact@v4
        with:
          name: snapshot-android
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 60