---
# File: .github/workflows/snapshot-ci.yml
name: Snapshot CI

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
         flutter-version: 3.32.6
      - run: flutter pub get
      - run: flutter build web --release
      - run: zip -r web.zip build/web
      - uses: actions/upload-artifact@v4
        with:
          name: web-snapshot
          path: web.zip

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
         flutter-version: 3.32.6
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v3
        with:
          name: android-snapshot
          path: build/app/outputs/flutter-apk/app-release.apk

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
         flutter-version: 3.32.6
      - run: flutter pub get
      - run: flutter build linux
      - run: zip -r linux.zip build/linux
      - uses: actions/upload-artifact@v3
        with:
          name: linux-snapshot
          path: linux.zip

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
         flutter-version: 3.32.6
      - run: flutter pub get
      - run: flutter build windows
      - run: Compress-Archive -Path build/windows -DestinationPath windows.zip
      - uses: actions/upload-artifact@v3
        with:
          name: windows-snapshot
          path: windows.zip

  build-macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
         flutter-version: 3.32.6
      - run: flutter pub get
      - run: flutter build macos --release
      - run: zip -r macos.zip build/macos/Build/Products/Release/Runner.app
      - uses: actions/upload-artifact@v3
        with:
          name: macos-snapshot
          path: macos.zip
  
  upload-artifacts:
    name: Upload Snapshot Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: snapshot-latest
          name: "Daily Snapshot Build (${{ github.sha }})"
          body: |
            Latest Snapshot Build

            This is an automated daily snapshot build from the `development` branch.

            Commit SHA: `${{ github.sha }}`
            Triggered by: `${{ github.event_name }}`

            Artifacts:
            - Web: web-snapshot.zip
            - Linux: linux-snapshot.zip
            - Windows: windows-snapshot.zip
            - Android: android-snapshot.apk
            - macOS: macos-snapshot.zip

            Please test thoroughly and report any issues.
          prerelease: true
          files: |
            web-snapshot.zip
            linux-snapshot.zip
            windows-snapshot.zip
            android-snapshot.apk
            macos-snapshot.zip

