# File: .github/workflows/flutter-release.yml
name: Release Production Build

on:
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  semantic-release:
    name: Run Semantic Release
    runs-on: ubuntu-latest
    outputs:
        version: ${{ steps.extract_version.outputs.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Prepare .releaserc
        run: mv .releaserc.prod.json .releaserc.json

      - name: Run Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          branch: main
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            semantic-release-pub
            @semantic-release/github
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_FOR_WORKFLOW_TRIGGER }}
          
      - name: Extract Version
        id: extract_version
        run: |
            version=$(grep '^version:' pubspec.yaml | cut -d' ' -f2)
            echo "version=$version" >> $GITHUB_OUTPUT

  build-web:
    needs: semantic-release
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.6
      - run: flutter pub get
      - run: flutter build web --release
      - run: zip -r web.zip build/web
      - uses: actions/upload-artifact@v4
        with:
          name: web-release
          path: web.zip

  build-android:
    needs: semantic-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.6
      - name: Get Flutter Dependencies
        run: flutter pub get
      - name: Build Android APK Release
        run: flutter build apk --release
      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: build/app/outputs/flutter-apk/app-release.apk


  build-linux:
    needs: semantic-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.6
      - name: Install Linux Dependencies
        run: sudo apt-get update && sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev
      - name: Enable Linux Desktop
        run: flutter config --enable-linux-desktop
      - name: Get Flutter Dependencies
        run: flutter pub get
      - name: Build Linux Release
        run: flutter build linux --release
      - name: Zip Linux Artifact
        run: zip -r linux.zip build/linux/x64/release/bundle
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-release
          path: linux.zip

  build-windows:
    needs: semantic-release
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.6
      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop
      - name: Get Flutter Dependencies
        run: flutter pub get
      - name: Build Windows Release
        run: flutter build windows --release
      - name: Zip Windows Artifact
        run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath windows.zip
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: windows.zip

  build-macos:
    needs: semantic-release
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.6
      - run: flutter pub get
      - run: flutter build macos --release
      - run: zip -r macos.zip build/macos/Build/Products/Release/chummer5x.app
      - uses: actions/upload-artifact@v4
        with:
          name: macos-release
          path: macos.zip

  publish-release:
    needs:
      - build-web
      - build-android
      - build-linux
      - build-windows
      - build-macos
      - semantic-release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.semantic-release.outputs.version }}
          name: Release v${{ needs.semantic-release.outputs.version }}
          prerelease: false
          draft: false
          files: |
            dist/web-release/web.zip
            dist/android-release/app-release.apk
            dist/linux-release/linux.zip
            dist/windows-release/windows.zip
            dist/macos-release/macos.zip